//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaDeIdentificacionUsuarios.RecursosReutilizables {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Idioma {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Idioma() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SistemaDeIdentificacionUsuarios.RecursosReutilizables.Idioma", typeof(Idioma).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Acceder.
        /// </summary>
        public static string btnACCEDER {
            get {
                return ResourceManager.GetString("btnACCEDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Capturar.
        /// </summary>
        public static string btnCAPTURAR {
            get {
                return ResourceManager.GetString("btnCAPTURAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Iniciar.
        /// </summary>
        public static string btnINICIAR {
            get {
                return ResourceManager.GetString("btnINICIAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Capturar.
        /// </summary>
        public static string btnREGISTRAR {
            get {
                return ResourceManager.GetString("btnREGISTRAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Salir.
        /// </summary>
        public static string btnSALIR {
            get {
                return ResourceManager.GetString("btnSALIR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Verificar.
        /// </summary>
        public static string btnVERIFICAR {
            get {
                return ResourceManager.GetString("btnVERIFICAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre.
        /// </summary>
        public static string Column1 {
            get {
                return ResourceManager.GetString("Column1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Primer apellido.
        /// </summary>
        public static string Column2 {
            get {
                return ResourceManager.GetString("Column2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Segundo apellido.
        /// </summary>
        public static string Column3 {
            get {
                return ResourceManager.GetString("Column3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Correo.
        /// </summary>
        public static string Column4 {
            get {
                return ResourceManager.GetString("Column4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipo de usuario.
        /// </summary>
        public static string Column6 {
            get {
                return ResourceManager.GetString("Column6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Imagen del rostro.
        /// </summary>
        public static string Column7 {
            get {
                return ResourceManager.GetString("Column7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Imagen dactilar.
        /// </summary>
        public static string Column8 {
            get {
                return ResourceManager.GetString("Column8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Bienvenid@, favor de escanear la huella dactilar..
        /// </summary>
        public static string lblBIENVENIDA {
            get {
                return ResourceManager.GetString("lblBIENVENIDA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Escoge la cámara:.
        /// </summary>
        public static string lblCOMENTARIO {
            get {
                return ResourceManager.GetString("lblCOMENTARIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Confirmar contraseña.
        /// </summary>
        public static string lblCONFIRMARPASS {
            get {
                return ResourceManager.GetString("lblCONFIRMARPASS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Correo Electrónico:.
        /// </summary>
        public static string lblCORREO {
            get {
                return ResourceManager.GetString("lblCORREO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha.
        /// </summary>
        public static string lblDATE {
            get {
                return ResourceManager.GetString("lblDATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hora.
        /// </summary>
        public static string lblHOUR {
            get {
                return ResourceManager.GetString("lblHOUR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contraseña:.
        /// </summary>
        public static string lblINGRESARPASS {
            get {
                return ResourceManager.GetString("lblINGRESARPASS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre:.
        /// </summary>
        public static string lblNAME {
            get {
                return ResourceManager.GetString("lblNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usuario:.
        /// </summary>
        public static string lblNOMBREUSUARIO {
            get {
                return ResourceManager.GetString("lblNOMBREUSUARIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contraseña:.
        /// </summary>
        public static string lblPASSORIGINAL {
            get {
                return ResourceManager.GetString("lblPASSORIGINAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contraseña incorrecta.
        /// </summary>
        public static string lblPASSWORD {
            get {
                return ResourceManager.GetString("lblPASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Primer Apellido:.
        /// </summary>
        public static string lblPRIMERAPELLIDO {
            get {
                return ResourceManager.GetString("lblPRIMERAPELLIDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Segundo Apellido:.
        /// </summary>
        public static string lblSEGUNDOAPELLIDO {
            get {
                return ResourceManager.GetString("lblSEGUNDOAPELLIDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipo de Usuario:.
        /// </summary>
        public static string lblTIPOUSUARIO {
            get {
                return ResourceManager.GetString("lblTIPOUSUARIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Capture la foto.
        /// </summary>
        public static string lblTITULO {
            get {
                return ResourceManager.GetString("lblTITULO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sistema de Control de Asistencia.
        /// </summary>
        public static string lblTITULO1 {
            get {
                return ResourceManager.GetString("lblTITULO1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sesión Administrador.
        /// </summary>
        public static string lblTITULO2 {
            get {
                return ResourceManager.GetString("lblTITULO2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Capture su huella dactilar.
        /// </summary>
        public static string lblTITULODACTILAR {
            get {
                return ResourceManager.GetString("lblTITULODACTILAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a (1. Administrador, 2. Operador).
        /// </summary>
        public static string lblUSUARIO {
            get {
                return ResourceManager.GetString("lblUSUARIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Acerca de.
        /// </summary>
        public static string tsbACERCADE {
            get {
                return ResourceManager.GetString("tsbACERCADE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Agregar.
        /// </summary>
        public static string tsbAGREGAR {
            get {
                return ResourceManager.GetString("tsbAGREGAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Consultar.
        /// </summary>
        public static string tsbCONSULTAR {
            get {
                return ResourceManager.GetString("tsbCONSULTAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Eliminar.
        /// </summary>
        public static string tsbELIMINAR {
            get {
                return ResourceManager.GetString("tsbELIMINAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Idioma.
        /// </summary>
        public static string tsbIDIOMA {
            get {
                return ResourceManager.GetString("tsbIDIOMA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Limpiar.
        /// </summary>
        public static string tsbLIMPIAR {
            get {
                return ResourceManager.GetString("tsbLIMPIAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Modificar.
        /// </summary>
        public static string tsbMODIFICAR {
            get {
                return ResourceManager.GetString("tsbMODIFICAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Salir.
        /// </summary>
        public static string tsbSALIR {
            get {
                return ResourceManager.GetString("tsbSALIR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Selección del idioma:.
        /// </summary>
        public static string tsbSELECCIONIDIOMA {
            get {
                return ResourceManager.GetString("tsbSELECCIONIDIOMA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Español.
        /// </summary>
        public static string tsmESPANISH {
            get {
                return ResourceManager.GetString("tsmESPANISH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingles.
        /// </summary>
        public static string tsmINGLES {
            get {
                return ResourceManager.GetString("tsmINGLES", resourceCulture);
            }
        }
    }
}
